<a href="https://colab.research.google.com/github/Saketh-Gurram/ML/blob/main/housing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing libraries


In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

Importing the dataset

In [ ]:
dataset = pd.read_csv('Housing.csv')
X = dataset.iloc[: , 1:].values
y = dataset.iloc[: , 0].values

FileNotFoundError: ignored

In [ ]:
print(X)

[[7420 4 2 ... 2 'yes' 'furnished']
 [8960 4 4 ... 3 'no' 'furnished']
 [9960 3 2 ... 2 'yes' 'semi-furnished']
 ...
 [3620 2 1 ... 0 'no' 'unfurnished']
 [2910 3 1 ... 0 'no' 'furnished']
 [3850 3 1 ... 0 'no' 'unfurnished']]


In [ ]:
print(y)

Encoding the values

In [ ]:
CT = [-1,-2,10,8,7,6,5,4]

In [ ]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), CT)], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 2 3 2]
 [1.0 0.0 0.0 ... 4 4 3]
 [0.0 1.0 0.0 ... 2 2 2]
 ...
 [0.0 0.0 1.0 ... 1 1 0]
 [1.0 0.0 0.0 ... 1 1 0]
 [0.0 0.0 1.0 ... 1 2 0]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mae = mean_absolute_error(y_test, y_pred)



# Mean Squared Error (MSE)
mse = mean_squared_error(y_test, y_pred)



# Root Mean Squared Error (RMSE)
rmse = np.sqrt(mse)



# R-squared (R2) score
r2 = r2_score(y_test, y_pred)



print(f"MAE: {mae:.2f}")
print(f"MSE: {mse:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R2 Score: {r2:.2f}")

MAE: 716231.12
MSE: 976484771024.59
RMSE: 988172.44
R2 Score: 0.66


In [ ]:
plt.scatter(y_test, y_pred)
plt.xlabel("Actual Values")
plt.ylabel("Predicted Values")
plt.title("Actual vs. Predicted Values")
plt.show()

NameError: ignored

In [ ]:
print(regressor.predict([[1,1,0,0,1,0,0,1,1,1,1,1,0,0,1,0,1,1,1,0,1,0,1,1,0,1,1,1,0,7420,4,3,2,4]]))

[-1.63e+09]


In [ ]:
print()